# Dependencies
markdown:         Kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
site:         
title:            PirateGrunt
tagline:          'Pirate Grunt'
description:      'Pirates, grunts, etc'
theme:            Superhero

author:
  name:           'Brian A. Fannin'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/PirateGrunt/PirateGrunt.github.io
