---
title: "Adventures in color"
author: "Brian A. Fannin"
output: html_document
---

Simple things rarely are. What I'd like to do is manually construct the colors for a plot, using the ggplot2 library.

https://www.stat.auckland.ac.nz/~ihaka/787/lectures-colour.pdf

Let's start with some basic categorical data. We've got continuous responses for two groups, labelled x and y. We'll construct it column-wise, then melt it.

```{r}
x <- seq_len(10)
y <- rnorm(x)
z <- rnorm(x)

mdf <- tidyr::gather(data.frame(x, y, z), group, value, y, z)
```

Very simple thing. Let's say that we want to map group y to red and group z to blue.

```{r }
library(ggplot2)
myColor <- scale_color_brewer(palette = "Blues")
myOtherColor <- scale_color_hue(h.start = 50)

pltBase <- ggplot(mdf, aes(x = x, y = value, group = group, color = group)) + geom_line()
pltBase
pltBase + myColor
pltBase + myOtherColor

dummyGroup <- as.factor(rep(1, nrow(df)))
pltBase2 <- ggplot(df, aes(x = x, y = y, color = "a")) + geom_line()
pltBase2
pltBase2 <- ggplot(df, aes(x = x, y = y, color = "b")) + geom_line()
pltBase2
pltBase2 + myColor
pltBase2 + myOtherColor

pltBase2 + guides(color = "none") + myOtherColor

```

http://stackoverflow.com/questions/8197559/emulate-ggplot2-default-color-palette

```{r }

gg_color_hue <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=65, c=100)[1:n]
}

n <- 4
plot(1:n, pch=16, cex=2, col=gg_color_hue(n))

n <- 10
plot(1:n, pch=16, cex=2, col=gg_color_hue(n))

x <- seq(0, 1, length.out = 25)
show_col(seq_gradient_pal()(x))
show_col(seq_gradient_pal("#f05f2c", "#090b0a")(x))

```

```{r}
plotColors <- function(n){
  df <- data.frame(group = head(letters, n), value = 1:n)
  plt <- ggplot(df, aes(x = group, y = value, fill = group)) + geom_bar(stat = "identity")
  plt
}

plotColors(2)
plotColors(3)
plotColors(4)
plotColors(5)
plotColors(6)
plotColors(10)
plotColors(20)
plotColors(26)

seq(15, 375, length=2+1)[1:2]
seq(15, 375, length=3+1)[1:3]
seq(15, 375, length=4+1)[1:4]
seq(15, 375, length=5+1)[1:5]
seq(15, 375, length=6+1)[1:6]
seq(15, 375, length=7+1)[1:7]

x <- 
y <- seq(15, 375, length=7+1)[7]

compare2 <- function(n1, n2){
  scales::show_col(hcl(h=c(seq(15, 375, length=n1+1)[n1]
                         , seq(15, 375, length=n2+1)[n2])
                     , l=65, c=100))  
}

compare2(5, 6)
```

